server.address=127.0.0.1
server.port=8081
spring.application.name=user-service
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
jwt.secret=

