spring.application.name=p2p-service
server.address=127.0.0.1
server.port=${P2P_SERVICE_PORT:8084}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

