spring.application.name=financeX-core
server.port=${GATEWAY_PORT:8080}
server.address=0.0.0.0

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Downstream Microservices URLs (Internal Loopback by Default)
services.user.url=${USER_SERVICE_URL:http://127.0.0.1:8081}
services.expense.url=${EXPENSE_SERVICE_URL:http://127.0.0.1:8082}
services.p2p.url=${P2P_SERVICE_URL:http://127.0.0.1:8084}
services.creditcard.url=${CREDITCARD_SERVICE_URL:http://127.0.0.1:8086}

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
